name: zenscape_ar_tourism
description: "A new Flutter project for AR-powered heritage tourism in Kerala."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter packages
  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  web: ^0.1.4-beta

  # UI and responsive design
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  fl_chart: ^0.66.0

  # Camera and media
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  geolocator: ^10.1.0
  record: ^5.0.4
  path_provider: ^2.1.1

  # Calendar and utilities
  table_calendar: ^3.0.9
  universal_html: ^2.2.4

  # Voice search
  speech_to_text: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/
    - assets/textures/
    - assets/icons/achievements/
    - assets/icons/badges/
    - assets/icons/challenges/
